/** @type {import('tailwindcss').Config} */
export default {
    content: [
        "./index.html",
        "./src/**/*.{js,ts,jsx,tsx}",
    ],
    darkMode: 'class',
    theme: {
        extend: {
            colors: {
                // Client-side colors
                'deep-red': {
                    DEFAULT: '#D62323',
                    50: '#FEF2F2',
                    100: '#FEE2E2',
                    200: '#FECACA',
                    300: '#FCA5A5',
                    400: '#F87171',
                    500: '#EF4444',
                    600: '#D62323',
                    700: '#B91C1C',
                    800: '#991B1B',
                    900: '#7F1D1D',
                },
                'lemon-yellow': {
                    DEFAULT: '#FCE94F',
                    50: '#FFFEF0',
                    100: '#FFFBDB',
                    200: '#FEF6B8',
                    300: '#FEF08A',
                    400: '#FDE85F',
                    500: '#FCE94F',
                    600: '#FACC15',
                    700: '#EAB308',
                    800: '#CA8A04',
                    900: '#A16207',
                },
                'royal-blue': {
                    DEFAULT: '#2B6CB0',
                    50: '#EFF6FF',
                    100: '#DBEAFE',
                    200: '#BFDBFE',
                    300: '#93C5FD',
                    400: '#60A5FA',
                    500: '#3B82F6',
                    600: '#2B6CB0',
                    700: '#1D4ED8',
                    800: '#1E40AF',
                    900: '#1E3A8A',
                },
                // Admin grayscale
                'admin-gray': {
                    50: '#F8F8F8',
                    100: '#F3F4F6',
                    200: '#E5E7EB',
                    300: '#D1D5DB',
                    400: '#9CA3AF',
                    500: '#6B7280',
                    600: '#4B5563',
                    700: '#374151',
                    800: '#1F2937',
                    900: '#111827',
                },
            },
            fontFamily: {
                sans: ['Inter', 'system-ui', 'sans-serif'],
                hindi: ['Noto Sans Devanagari', 'system-ui', 'sans-serif'],
            },
            fontSize: {
                'xs': ['0.75rem', { lineHeight: '1.5' }],
                'sm': ['0.875rem', { lineHeight: '1.5' }],
                'base': ['1rem', { lineHeight: '1.75' }],
                'lg': ['1.125rem', { lineHeight: '1.75' }],
                'xl': ['1.25rem', { lineHeight: '1.75' }],
                '2xl': ['1.5rem', { lineHeight: '2' }],
                '3xl': ['1.875rem', { lineHeight: '2.25' }],
                '4xl': ['2.25rem', { lineHeight: '2.5' }],
                '5xl': ['3rem', { lineHeight: '1' }],
                '6xl': ['3.75rem', { lineHeight: '1' }],
            },
            spacing: {
                '18': '4.5rem',
                '88': '22rem',
                '100': '25rem',
                '112': '28rem',
                '128': '32rem',
            },
            borderRadius: {
                'sm': '6px',
                'DEFAULT': '8px',
                'md': '10px',
                'lg': '12px',
                'xl': '16px',
            },
            boxShadow: {
                'soft': '0 2px 8px rgba(0, 0, 0, 0.08)',
                'soft-lg': '0 4px 16px rgba(0, 0, 0, 0.12)',
            },
        },
    },
    plugins: [],
}
